version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  minh-postgres:
    image: postgres:latest
    container_name: minh-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: vnuser
      POSTGRES_PASSWORD: vnpass

  minh-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: minh-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
