version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  vietnam-postgres:
    image: postgres:latest
    container_name: vietnam-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: vnuser
      POSTGRES_PASSWORD: vnpass
