---
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas: {}
  securitySchemes: {}
info:
  title: '@chatbot/apis'
  version: '0.0.1'
  description: 'APIs'
  license:
    name: 'MIT'
  contact:
    name: 'hieudoanm '
    email: 'hieumdoan@gmail.com'
openapi: '3.0.0'
paths:
  /api/vnindex/history/{symbol}/chart:
    get:
      operationId: 'ChartifyHistory'
      responses:
        200:
          description: 'Chart SVG'
          content:
            application/json:
              schema:
                type: 'number'
                enum:
                  - null
                nullable: true
      tags:
        - 'VNINDEX'
      security: []
      parameters:
        - in: 'path'
          name: 'symbol'
          required: true
          schema:
            type: 'string'
        - in: 'query'
          name: 'width'
          required: false
          schema:
            default: 500
            format: 'double'
            type: 'number'
        - in: 'query'
          name: 'height'
          required: false
          schema:
            default: 100
            format: 'double'
            type: 'number'
        - in: 'query'
          name: 'minValue'
          required: false
          schema:
            default: 0
            format: 'double'
            type: 'number'
        - in: 'query'
          name: 'maxValue'
          required: false
          schema:
            default: 200
            format: 'double'
            type: 'number'
        - in: 'query'
          name: 'strokeColor'
          required: false
          schema:
            default: '#0074d9'
            type: 'string'
        - in: 'query'
          name: 'strokeWidth'
          required: false
          schema:
            default: 2
            format: 'double'
            type: 'number'
servers:
  - url: '/'
