serve:
		go run main.go

ngrok:
		ngrok http 8080

build:
		go build main.go

start:
		./main

send-football:
		go run scripts/telegram/messages/football/main.go

send-forex:
		go run scripts/telegram/messages/forex/main.go

send-news:
		go run scripts/telegram/messages/news/main.go

send-weather:
		go run scripts/telegram/messages/weather/main.go
