serve:
		go run main.go

build:
		go build main.go

start:
		./main

send-news:
		go run scripts/telegram/messages/football/main.go

send-weather:
		go run scripts/telegram/messages/forex/main.go

send-news:
		go run scripts/telegram/messages/news/main.go

send-weather:
		go run scripts/telegram/messages/weather/main.go
