name: CI - Node.js

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**

jobs:
  github-actions:
    strategy:
      fail-fast: false
      matrix:
        node:
          - name: Node.js 18
            version: 18.x
        os:
          - name: Ubuntu
            version: ubuntu-latest
        project:
          - app-name: Web
            working-directory: ./services/web
    name: ${{ matrix.os.name }} - ${{ matrix.node.name }} - ${{ matrix.project.app-name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node.version }}
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Build Production
        run: yarn build
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Unit Test
        run: yarn test
        working-directory: ${{ matrix.project.working-directory }}
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
